### ISSUE TITLE
Huge fills cause pain

### ISSUE THREAD

**Issue by dy** [madbence/node-drawille-canvas#5]
This code takes very long to render.

``` js
canvas.fillRect(0,0,9999,9999);
```

There should be some slicing I suppose?

**Comment by madbence** [comment]
yup, rasterization ignores the viewport completly right now. `fillRect` right now just paints 2 triangles, using [`bresenham`](https://npmjs.com/bresenham). viewport clipping is actually quite complicated :crying_cat_face:

**Comment by dy** [comment]
it seems that it is able to clamp input values before any matrix operations go on. That isn't difficult - anyways user would have to do it manually now)

**Comment by dy** [comment]
Closed by #6
