### ISSUE TITLE
Upgrade gl-matrix dependence to the latest version to prevent install a local `npm`

### ISSUE THREAD

**Issue by huan** [madbence/node-drawille-canvas#9]
According to https://github.com/toji/gl-matrix/pull/307

We should not install `npm` ad a peer dependency instead of a dev dependency.

So please upgrade the `gl-matrix` to the latest version to prevent this problem.

**Comment by jgwillard** [comment]
Should this repo be considered to be abandoned? There's a PR that's been sitting for 1.5 years now.

**Comment by dy** [comment]
Published
